### PR TITLE
Passthrough text/css

### LINKED ISSUE #123: Using text/css breaks ability of built app to serve CSS files
I've been fighting this for days now...

When using `electron-packager-compile` to build a project (At least, for Darwin; I haven't tried any other platforms), renderer CSS files served via:

`<link rel="stylesheet" type="text/css" href="index.css">`

...Get transferred as empty `text/plain` files in the built app and thus do not render. However, they transfer perfectly fine if running the app via `electron .`. 

Even more confusing, `text/less` files have no problem.

I've created an example repo depicting this here: https://github.com/aendrew/electron-compile-no-css-example

Note that if you run `npm electron`, you see the square as red — this is because both the LESS and CSS files are loading, but the latter is taking precedence. 

If you then run `npm start` (which does a build and opens the built app), you get a green square — this is because the LESS is loading, but the CSS is not. 

For now, one workaround is just to rename all CSS files to LESS and include as such.

### PR DESCRIPTION
**Pull request by simongregory**
This fixes [electron-compile#123](https://github.com/electron/electron-compile/issues/123)

### CODE REVIEW

**Comment by simongregory** [comment]
Whilst this may fix the specific problem of `text/css` files not getting passed through it looks as though there's a wider issue to solve. In my case `application/dash+xml` fail in the same way, first attempt is going to be to setup the `fallbackCompiler` to handle anything unknown but I can't help thinking there's a better way to be doing this.

**Comment by zeke** [comment]
This seems fine, but is there an automated way to test it?

**Comment by mnquintana** [comment]
Will this break Less compilation? I think we might wanna re-work the MIME type for Less anyway (since it's set to `text/css` right now too)

**Comment by michaelenger** [comment]
@mnquintana Doesn't the compiler look for the `text/less` mimetype?
https://github.com/electron/electron-compilers/blob/c662baa5e55487bc119eb20d42619339f6929391/src/css/less.js#L4

**Comment by anaisbetts** [comment]
This should already be fixed, if not please reopen!

**Pull request closed without merging**
